### ISSUE TITLE
Select Default and Run Configuration Specific Test Category

### ISSUE THREAD

**Issue by grabnerandi** [Dynatrace/Dynatrace-Eclipse-Integration-Plugin#1]
Hi
Right now the Integration works well for regular Unit Tests as the Plugin as the plugin automatically registers a "Unit Test". The problem with that is that we are constraint to the measures that are analyzed for Unit Tests. 
For some scenarios our developers want to also analyze execution times of Tests, Database or Web Requests. Thats why we would like to have the option to specify the Test Category that is used by the Eclipse Plugin when registering a test run. It would be great to have a Default Selection in the global settings and then an option to specify the Test Category also in every Run Configuration

Andi

**Comment by grabnerandi** [comment]
When executing a larger number of Tests the current Result View is getting a bit hard to use. The main use case is for a developer to quickly spot those tests that have a regression. I therefore suggest to provide filtering options per Test State so that I can easily and quickly identify those test runs that just degraded.
In order to also know what exactly degraded it would be necessary to not only see the current value of every metric but also see the min and max expected value range

**Comment by micmich** [comment]
Please see screenshots in readme.md and download the latest release.

**Comment by grabnerandi** [comment]
Thank you!! Works great! Now - I need to ask for my second request that I put in. The Dynatrace Result Table in Eclipse would need a slight update as well to become really useful
#1: Add additional columns, e.g: Agent, Expected Min, Expected Max
#2: Make the whole table filter / sortable, e.g: only show me the failed or degraded tests

Will add more details to my other Issue on GH. Thanks again for this extension though!!
